#!/usr/bin/env python3
"""
Phase-2 cloze re-curation content — 18 files re-authored from scratch.

Each entry: (relative path, deck-level header, list of (Text, Reading, Hint)).
The Text contains exactly one {{c1::TARGET}} marker; Reading mirrors with
the same marker around the kana of the target; Hint is a short situational
English cue (NOT the answer paraphrased).

Audio is left empty (Audio column = "") and `scaffold:pending-audio` is
added to tags — these are new sentences without recorded audio.

Tags: module:<mod> jlpt:<level> point:<slug> complexity:standard
      source:authored frequency:top10k scaffold:pending-audio
"""
from pathlib import Path

# (deck_path, jlpt_level, module_dir, slug, freq_default, rows)
# rows = [(text, reading, hint, freq_override_or_None, complexity_override_or_None)]

CONTENT = [
    # ── Track 2A: 14 files with 100% off-topic content ───────────────────────
    {
        "path": "grammar-strict/04-n2/ものか_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "ものか",
        "rows": [
            ("学生のあなたにわかる{{c1::ものか}}。",
             "がくせいのあなたにわかる{{c1::ものか}}。",
             "emphatic denial — student couldn't possibly understand",
             "top10k", "intro"),
            ("二度とあそこへ行く{{c1::ものか}}。",
             "にどとあそこへいく{{c1::ものか}}。",
             "refusing to repeat — never again",
             "top10k", "standard"),
            ("諦める{{c1::ものか}}、最後までやる。",
             "あきらめる{{c1::ものか}}、さいごまでやる。",
             "refusing to quit — see it through",
             "top10k", "standard"),
            ("彼が約束を破る{{c1::ものか}}。",
             "かれがやくそくをやぶる{{c1::ものか}}。",
             "defending someone's character — no way",
             "low", "standard"),
            ("こんな失敗、もうする{{c1::ものか}}。",
             "こんなしっぱい、もうする{{c1::ものか}}。",
             "self-warning — won't repeat the mistake",
             "top10k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/まで_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "まで",
        "rows": [
            ("朝{{c1::まで}}起きていた。",
             "あさ{{c1::まで}}おきていた。",
             "temporal extent — until morning",
             "top1k", "intro"),
            ("子供に{{c1::まで}}笑われた。",
             "こどもに{{c1::まで}}わらわれた。",
             "emphatic extent — even by children",
             "top10k", "standard"),
            ("そこ{{c1::まで}}疲れているとは思わなかった。",
             "そこ{{c1::まで}}つかれているとはおもわなかった。",
             "extent of state — that exhausted",
             "top5k", "standard"),
            ("死ぬ{{c1::まで}}頑張ると約束した。",
             "しぬ{{c1::まで}}がんばるとやくそくした。",
             "limit of commitment — until I die",
             "low", "standard"),
            ("駅{{c1::まで}}歩いた。",
             "えき{{c1::まで}}あるいた。",
             "spatial endpoint — to the station",
             "top1k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/と考えられる_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "と考えられる",
        "rows": [
            ("経済はすでに回復した{{c1::と考えられる}}。",
             "けいざいはすでにかいふくした{{c1::とかんがえられる}}。",
             "formal inference — economy recovered",
             "low", "standard"),
            ("事故の原因は整備不良にある{{c1::と考えられる}}。",
             "じこのげんいんはせいびふりょうにある{{c1::とかんがえられる}}。",
             "formal cause analysis",
             "low", "standard"),
            ("この遺跡は紀元前のものだ{{c1::と考えられる}}。",
             "このいせきはきげんぜんのものだ{{c1::とかんがえられる}}。",
             "archaeological inference",
             "low", "standard"),
            ("彼の主張は妥当{{c1::と考えられる}}。",
             "かれのしゅちょうはだとう{{c1::とかんがえられる}}。",
             "academic agreement — reasonable",
             "low", "standard"),
            ("環境への影響は大きい{{c1::と考えられる}}。",
             "かんきょうへのえいきょうはおおきい{{c1::とかんがえられる}}。",
             "environmental impact estimate",
             "top10k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/てたまらない_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "てたまらない",
        "rows": [
            ("今日は暑く{{c1::てたまらない}}。",
             "きょうはあつく{{c1::てたまらない}}。",
             "sensation — unbearable heat",
             "top1k", "intro"),
            ("彼女に会いたく{{c1::てたまらない}}。",
             "かのじょにあいたく{{c1::てたまらない}}。",
             "desire — missing someone",
             "top5k", "intro"),
            ("眠く{{c1::てたまらない}}。",
             "ねむく{{c1::てたまらない}}。",
             "sensation — overwhelming sleepiness",
             "top1k", "intro"),
            ("結果が気になっ{{c1::てたまらない}}。",
             "けっかがきになっ{{c1::てたまらない}}。",
             "mental state — can't stop wondering",
             "top10k", "standard"),
            ("喉が渇い{{c1::てたまらない}}。",
             "のどがかわい{{c1::てたまらない}}。",
             "sensation — desperately thirsty",
             "top10k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/にもかかわらず_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "にもかかわらず",
        "rows": [
            ("雨{{c1::にもかかわらず}}、試合は予定通り行われた。",
             "あめ{{c1::にもかかわらず}}、しあいはよていどおりおこなわれた。",
             "weather defied",
             "top10k", "standard"),
            ("努力した{{c1::にもかかわらず}}、結果は出なかった。",
             "どりょくした{{c1::にもかかわらず}}、けっかはでなかった。",
             "effort vs outcome",
             "top10k", "standard"),
            ("警告した{{c1::にもかかわらず}}、彼は無視した。",
             "けいこくした{{c1::にもかかわらず}}、かれはむしした。",
             "warning ignored",
             "low", "standard"),
            ("高齢である{{c1::にもかかわらず}}、彼は今も現役だ。",
             "こうれいである{{c1::にもかかわらず}}、かれはいまもげんえきだ。",
             "age defied",
             "low", "standard"),
            ("危険を承知している{{c1::にもかかわらず}}、彼は続けた。",
             "きけんをしょうちしている{{c1::にもかかわらず}}、かれはつづけた。",
             "knowing the risk",
             "low", "standard"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/および_cloze.tsv",
        "deck": "04 - N2",
        "module": "04-n2",
        "jlpt": "n2",
        "slug": "および",
        "rows": [
            ("日本{{c1::および}}中国の経済関係について述べる。",
             "にほん{{c1::および}}ちゅうごくのけいざいかんけいについてのべる。",
             "formal listing — two regions",
             "top10k", "standard"),
            ("男性{{c1::および}}女性が対象である。",
             "だんせい{{c1::および}}じょせいがたいしょうである。",
             "formal listing — both groups",
             "top10k", "intro"),
            ("技術{{c1::および}}知識が必要だ。",
             "ぎじゅつ{{c1::および}}ちしきがひつようだ。",
             "formal listing — two requirements",
             "top10k", "intro"),
            ("東京{{c1::および}}周辺地域の住民が参加した。",
             "とうきょう{{c1::および}}しゅうへんちいきのじゅうみんがさんかした。",
             "formal listing — area and surroundings",
             "low", "standard"),
            ("学校{{c1::および}}家庭での教育が大切だ。",
             "がっこう{{c1::および}}かていでのきょういくがたいせつだ。",
             "formal listing — two settings",
             "top10k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/ながらも_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "ながらも",
        "rows": [
            ("子供{{c1::ながらも}}、責任感がある。",
             "こども{{c1::ながらも}}、せきにんかんがある。",
             "concessive — despite being a child",
             "top10k", "standard"),
            ("残念{{c1::ながらも}}、規則は規則だ。",
             "ざんねん{{c1::ながらも}}、きそくはきそくだ。",
             "concessive — reluctant acceptance",
             "top5k", "standard"),
            ("小さい{{c1::ながらも}}、立派な家だ。",
             "ちいさい{{c1::ながらも}}、りっぱないえだ。",
             "concessive — small but fine",
             "top10k", "intro"),
            ("知ってい{{c1::ながらも}}、彼は教えなかった。",
             "しってい{{c1::ながらも}}、かれはおしえなかった。",
             "concessive — withheld despite knowing",
             "top10k", "standard"),
            ("貧しい{{c1::ながらも}}、家族は幸せだった。",
             "まずしい{{c1::ながらも}}、かぞくはしあわせだった。",
             "concessive — poor but happy",
             "low", "standard"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/に違いない_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "に違いない",
        "rows": [
            ("彼が犯人{{c1::に違いない}}。",
             "かれがはんにん{{c1::にちがいない}}。",
             "strong inference — must be the one",
             "top10k", "intro"),
            ("これは嘘{{c1::に違いない}}。",
             "これはうそ{{c1::にちがいない}}。",
             "strong inference — has to be a lie",
             "top5k", "standard"),
            ("試験に合格した{{c1::に違いない}}。",
             "しけんにごうかくした{{c1::にちがいない}}。",
             "strong inference — past event",
             "top10k", "standard"),
            ("彼女は怒っている{{c1::に違いない}}。",
             "かのじょはおこっている{{c1::にちがいない}}。",
             "strong inference — present state",
             "top5k", "intro"),
            ("これは本物{{c1::に違いない}}。",
             "これはほんもの{{c1::にちがいない}}。",
             "strong inference — authenticity",
             "top10k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/だらけ_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "だらけ",
        "rows": [
            ("部屋がほこり{{c1::だらけ}}だ。",
             "へやがほこり{{c1::だらけ}}だ。",
             "covered in — dust",
             "top10k", "intro"),
            ("間違い{{c1::だらけ}}のレポートを提出した。",
             "まちがい{{c1::だらけ}}のれぽーとをていしゅつした。",
             "full of — mistakes",
             "top5k", "standard"),
            ("子供は泥{{c1::だらけ}}になって帰ってきた。",
             "こどもはどろ{{c1::だらけ}}になってかえってきた。",
             "covered in — mud",
             "low", "intro"),
            ("借金{{c1::だらけ}}の人生はつらい。",
             "しゃっきん{{c1::だらけ}}のじんせいはつらい。",
             "buried in — debt",
             "low", "standard"),
            ("傷{{c1::だらけ}}の顔で帰ってきた。",
             "きず{{c1::だらけ}}のかおでかえってきた。",
             "covered in — wounds",
             "top10k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/につれて_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "につれて",
        "rows": [
            ("時間が経つ{{c1::につれて}}、痛みが和らいだ。",
             "じかんがたつ{{c1::につれて}}、いたみがやわらいだ。",
             "gradual — over time",
             "top5k", "standard"),
            ("年を取る{{c1::につれて}}、考え方が変わった。",
             "としをとる{{c1::につれて}}、かんがえかたがかわった。",
             "gradual — with age",
             "top10k", "standard"),
            ("経済が成長する{{c1::につれて}}、生活が豊かになった。",
             "けいざいがせいちょうする{{c1::につれて}}、せいかつがゆたかになった。",
             "gradual — with growth",
             "low", "standard"),
            ("高度が上がる{{c1::につれて}}、気温が下がる。",
             "こうどがあがる{{c1::につれて}}、きおんがさがる。",
             "proportional — physical law",
             "low", "standard"),
            ("経験を積む{{c1::につれて}}、自信がついた。",
             "けいけんをつむ{{c1::につれて}}、じしんがついた。",
             "gradual — with experience",
             "top10k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/っぽい_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "っぽい",
        "rows": [
            ("そんな子供{{c1::っぽい}}言い方はやめなさい。",
             "そんなこども{{c1::っぽい}}いいかたはやめなさい。",
             "-ish — childish manner",
             "top10k", "intro"),
            ("彼の話は嘘{{c1::っぽい}}。",
             "かれのはなしはうそ{{c1::っぽい}}。",
             "-ish — seems like a lie",
             "top5k", "intro"),
            ("最近、彼は怒り{{c1::っぽい}}。",
             "さいきん、かれはおこり{{c1::っぽい}}。",
             "-prone — tends to anger",
             "top10k", "standard"),
            ("彼女は男{{c1::っぽい}}話し方をする。",
             "かのじょはおとこ{{c1::っぽい}}はなしかたをする。",
             "-ish — masculine manner",
             "low", "standard"),
            ("私は忘れ{{c1::っぽい}}性格だ。",
             "わたしはわすれ{{c1::っぽい}}せいかくだ。",
             "-prone — forgetful tendency",
             "top10k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/せいで_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "せいで",
        "rows": [
            ("雨の{{c1::せいで}}、試合が中止になった。",
             "あめの{{c1::せいで}}、しあいがちゅうしになった。",
             "negative cause — weather",
             "top10k", "intro"),
            ("彼の{{c1::せいで}}失敗した。",
             "かれの{{c1::せいで}}しっぱいした。",
             "negative cause — blaming someone",
             "top5k", "intro"),
            ("寝坊した{{c1::せいで}}、遅刻してしまった。",
             "ねぼうした{{c1::せいで}}、ちこくしてしまった。",
             "negative cause — own fault",
             "top10k", "standard"),
            ("暑さの{{c1::せいで}}、食欲がない。",
             "あつさの{{c1::せいで}}、しょくよくがない。",
             "negative cause — discomfort",
             "top10k", "intro"),
            ("自分の{{c1::せいで}}、誰にも頼れない。",
             "じぶんの{{c1::せいで}}、だれにもたよれない。",
             "negative cause — self-blame",
             "low", "standard"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/ことがある_cloze.tsv",
        "deck": "03 - N3",
        "module": "03-n3",
        "jlpt": "n3",
        "slug": "ことがある",
        "rows": [
            ("朝寝坊する{{c1::ことがある}}。",
             "あさねぼうする{{c1::ことがある}}。",
             "sometimes — occasional habit",
             "top5k", "intro"),
            ("たまに京都へ行く{{c1::ことがある}}。",
             "たまにきょうとへいく{{c1::ことがある}}。",
             "sometimes — occasional trip",
             "top5k", "intro"),
            ("電車が遅れる{{c1::ことがある}}。",
             "でんしゃがおくれる{{c1::ことがある}}。",
             "sometimes — railway delay",
             "top1k", "intro"),
            ("彼は嘘をつく{{c1::ことがある}}。",
             "かれはうそをつく{{c1::ことがある}}。",
             "sometimes — character flaw",
             "top10k", "standard"),
            ("ストレスで眠れない{{c1::ことがある}}。",
             "すとれすでねむれない{{c1::ことがある}}。",
             "sometimes — sleep issue",
             "top10k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/に足る_cloze.tsv",
        "deck": "05 - N1",
        "module": "05-n1",
        "jlpt": "n1",
        "slug": "に足る",
        "rows": [
            ("信頼する{{c1::に足る}}人物だ。",
             "しんらいする{{c1::にたる}}じんぶつだ。",
             "worthy of — trust",
             "low", "standard"),
            ("一読する{{c1::に足る}}本である。",
             "いちどくする{{c1::にたる}}ほんである。",
             "worthy of — reading",
             "low", "standard"),
            ("称賛{{c1::に足る}}成果を上げた。",
             "しょうさん{{c1::にたる}}せいかをあげた。",
             "worthy of — praise",
             "low", "advanced"),
            ("検討{{c1::に足る}}提案を受けた。",
             "けんとう{{c1::にたる}}ていあんをうけた。",
             "worthy of — review",
             "low", "advanced"),
            ("注目{{c1::に足る}}発見だった。",
             "ちゅうもく{{c1::にたる}}はっけんだった。",
             "worthy of — attention",
             "low", "standard"),
        ],
    },

    # ── Track 2B: 4 whole-sentence cloze repairs ─────────────────────────────
    {
        "path": "grammar-strict/01-n5/ましょう_cloze.tsv",
        "deck": "01 - N5",
        "module": "01-n5",
        "jlpt": "n5",
        "slug": "ましょう",
        "rows": [
            ("一緒に映画を見{{c1::ましょう}}。",
             "いっしょにえいがをみ{{c1::ましょう}}。",
             "polite suggestion — invitation",
             "top1k", "intro"),
            ("公園で遊び{{c1::ましょう}}。",
             "こうえんであそび{{c1::ましょう}}。",
             "polite suggestion — activity",
             "top1k", "intro"),
            ("お茶を飲み{{c1::ましょう}}。",
             "おちゃをのみ{{c1::ましょう}}。",
             "polite suggestion — refreshment",
             "top1k", "intro"),
            ("明日また会い{{c1::ましょう}}。",
             "あしたまたあい{{c1::ましょう}}。",
             "polite suggestion — parting",
             "top1k", "intro"),
            ("もう少し待ち{{c1::ましょう}}。",
             "もうすこしまち{{c1::ましょう}}。",
             "polite suggestion — patience",
             "top1k", "intro"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/みたい_cloze.tsv",
        "deck": "02 - N4",
        "module": "02-n4",
        "jlpt": "n4",
        "slug": "みたい",
        "rows": [
            ("雨が降る{{c1::みたい}}だ。",
             "あめがふる{{c1::みたい}}だ。",
             "conjecture — looks like rain",
             "top1k", "intro"),
            ("彼は学生{{c1::みたい}}だ。",
             "かれはがくせい{{c1::みたい}}だ。",
             "comparison — looks like a student",
             "top1k", "intro"),
            ("子供{{c1::みたい}}に泣いている。",
             "こども{{c1::みたい}}にないている。",
             "comparison — like a child",
             "top1k", "intro"),
            ("風邪を引いた{{c1::みたい}}だ。",
             "かぜをひいた{{c1::みたい}}だ。",
             "conjecture — feels like a cold",
             "top1k", "intro"),
            ("本物{{c1::みたい}}に見える。",
             "ほんもの{{c1::みたい}}にみえる。",
             "comparison — looks real",
             "top5k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/るところだ_cloze.tsv",
        "deck": "02 - N4",
        "module": "02-n4",
        "jlpt": "n4",
        "slug": "るところだ",
        "rows": [
            ("今から出かける{{c1::ところだ}}。",
             "いまからでかける{{c1::ところだ}}。",
             "about to — leaving now",
             "top5k", "intro"),
            ("ちょうど食事を始める{{c1::ところだ}}。",
             "ちょうどしょくじをはじめる{{c1::ところだ}}。",
             "about to — meal starting",
             "top5k", "standard"),
            ("彼に電話をかける{{c1::ところだ}}。",
             "かれにでんわをかける{{c1::ところだ}}。",
             "about to — making a call",
             "top10k", "intro"),
            ("プロジェクトが完成する{{c1::ところだ}}。",
             "ぷろじぇくとがかんせいする{{c1::ところだ}}。",
             "about to — finishing project",
             "top10k", "standard"),
            ("今、会議が始まる{{c1::ところだ}}。",
             "いま、かいぎがはじまる{{c1::ところだ}}。",
             "about to — meeting begins",
             "top5k", "standard"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/ていく_cloze.tsv",
        "deck": "02 - N4",
        "module": "02-n4",
        "jlpt": "n4",
        "slug": "ていく",
        "rows": [
            ("街がどんどん変わっ{{c1::ていく}}。",
             "まちがどんどんかわっ{{c1::ていく}}。",
             "continuing change — away from now",
             "top5k", "standard"),
            ("これから気温が下がっ{{c1::ていく}}。",
             "これからきおんがさがっ{{c1::ていく}}。",
             "continuing change — future",
             "top10k", "intro"),
            ("子供たちは元気に走っ{{c1::ていった}}。",
             "こどもたちはげんきにはしっ{{c1::ていった}}。",
             "motion away — narrative past",
             "top5k", "intro"),
            ("友達は手を振りながら去っ{{c1::ていった}}。",
             "ともだちはてをふりながらさっ{{c1::ていった}}。",
             "motion away from speaker",
             "top10k", "standard"),
            ("技術はますます進歩し{{c1::ていく}}だろう。",
             "ぎじゅつはますますしんぽし{{c1::ていく}}だろう。",
             "continuing change — projection",
             "low", "standard"),
        ],
    },
]


def make_tsv(entry):
    """Generate TSV content for one entry."""
    deck = f"Japanese Grammar::{entry['deck']} Grammar::Cloze"
    header = (
        "#separator:tab\n"
        "#html:true\n"
        "#columns:Text\tReading\tHint\tAudio\tTags\n"
        "#notetype:Cloze\n"
        f"#deck:{deck}\n"
        "\n"
    )
    body_lines = []
    for text, reading, hint, freq, complexity in entry["rows"]:
        tags = (
            f"module:{entry['module']} "
            f"jlpt:{entry['jlpt']} "
            f"point:{entry['slug']} "
            f"complexity:{complexity} "
            f"source:authored "
            f"frequency:{freq} "
            f"scaffold:pending-audio"
        )
        # Audio column empty — scaffold:pending-audio in tags
        body_lines.append(f"{text}\t{reading}\t{hint}\t\t{tags}\n")
    return header + "".join(body_lines)


def main():
    for entry in CONTENT:
        path = Path(entry["path"])
        path.write_text(make_tsv(entry), encoding="utf-8")
        print(f"  WROTE {path}  ({len(entry['rows'])} rows)")
    print(f"\nTotal: {len(CONTENT)} cloze files re-authored.")


if __name__ == "__main__":
    main()
