#!/usr/bin/env python3
"""
Phase-9+ — re-author 37 recognition files that drifted from their
filename slug. Each file gets 5 fresh on-point rows.

Schema: JP\tReading\tEN\tLabel\tFormula\tMainUse\tQuickCue\tContrast\tAudio\tTags

The file-level fields (Label, Formula, Contrast) stay constant across
the 5 rows. MainUse + QuickCue vary per row (Phase-4 design).
Audio is empty + scaffold:pending-audio in tags.
"""
from pathlib import Path

# Each entry:
#   path:     repo-relative file path
#   module:   directory name
#   jlpt:     n5/n4/n3/n2/n1
#   slug:     the grammar slug (matches filename)
#   label:    file-level grammar identity (short)
#   formula:  morphological pattern
#   contrast: what this contrasts with (file-level)
#   rows:     list of (jp, reading, en, mainuse, quickcue)

CONTENT = [
    # ───────────────────── N5 ─────────────────────
    {
        "path": "grammar-strict/01-n5/くる_recognition.tsv",
        "module": "01-n5", "jlpt": "n5", "slug": "くる",
        "label": "くる (come, irregular カ変)",
        "formula": "Verb[て] + くる / motion + くる",
        "contrast": "くる = motion toward speaker; いく = motion away",
        "rows": [
            ("毎朝七時に学校へ来ます。", "まいあさしちじにがっこうへきます。",
             "I come to school at 7am every morning.",
             "くる: physical arrival — moving toward the speaker's location",
             "daily arrival"),
            ("子供たちが走って来た。", "こどもたちがはしってきた。",
             "The children came running.",
             "走ってくる: manner + motion-toward — children physically approached",
             "running approach"),
            ("コンビニで弁当を買って来ました。", "こんびにでべんとうをかってきました。",
             "I bought a bento at the convenience store (and came back).",
             "Verb-てくる: go-and-return — perform action elsewhere, then return here",
             "errand-and-return"),
            ("だんだん寒くなって来ましたね。", "だんだんさむくなってきましたね。",
             "It's been getting colder, hasn't it.",
             "なってくる: gradual change reaching the present moment",
             "gradual change toward now"),
            ("彼は明日また来るそうだ。", "かれはあしたまたくるそうだ。",
             "I hear he's coming again tomorrow.",
             "くる: scheduled visit — confirmed future arrival",
             "future visit"),
        ],
    },
    {
        "path": "grammar-strict/01-n5/する_recognition.tsv",
        "module": "01-n5", "jlpt": "n5", "slug": "する",
        "label": "する (do, irregular サ変)",
        "formula": "Noun + を + する / Noun + する",
        "contrast": "する = generic 'do'; やる = colloquial; 行う = formal",
        "rows": [
            ("毎日宿題をします。", "まいにちしゅくだいをします。",
             "I do homework every day.",
             "を-marked object + する: perform a discrete action",
             "doing homework"),
            ("週末はテニスをする予定です。", "しゅうまつはてにすをするよていです。",
             "I plan to play tennis on the weekend.",
             "スポーツ + する: engage in a sport",
             "sport activity"),
            ("彼は会社で仕事をしている。", "かれはかいしゃでしごとをしている。",
             "He's working at the office.",
             "仕事をする: be employed / be actively working",
             "be at work"),
            ("勉強しないと試験に落ちる。", "べんきょうしないとしけんにおちる。",
             "If you don't study, you'll fail the exam.",
             "N-する compound: noun + する becomes a single verb (勉強する)",
             "compound verb"),
            ("どうしますか。", "どうしますか。",
             "What will you do?",
             "どうする: how to act / what action to take",
             "asking for plan"),
        ],
    },
    {
        "path": "grammar-strict/01-n5/てはいけない_recognition.tsv",
        "module": "01-n5", "jlpt": "n5", "slug": "てはいけない",
        "label": "てはいけない (must not / prohibition)",
        "formula": "Verb[て] + は + いけない",
        "contrast": "てはいけない = strict prohibition; ないほうがいい = recommendation",
        "rows": [
            ("ここで写真を撮ってはいけません。", "ここでしゃしんをとってはいけません。",
             "You must not take photos here.",
             "Verb-てはいけない: institutional prohibition",
             "no photos"),
            ("授業中、話してはいけない。", "じゅぎょうちゅう、はなしてはいけない。",
             "You must not talk during class.",
             "ては + いけない: behavioral rule in formal setting",
             "classroom rule"),
            ("芝生に入ってはいけません。", "しばふにはいってはいけません。",
             "You must not enter the lawn.",
             "Verb-てはいけない: posted-sign prohibition",
             "park sign"),
            ("お酒を飲んで運転してはいけない。", "おさけをのんでうんてんしてはいけない。",
             "You must not drive after drinking alcohol.",
             "ては + いけない: legal/safety prohibition",
             "DUI prohibition"),
            ("ここで遊んではいけませんよ。", "ここであそんではいけませんよ。",
             "You're not allowed to play here.",
             "Verb-てはいけません + よ: speaker-issued warning",
             "warning a child"),
        ],
    },
    {
        "path": "grammar-strict/01-n5/ないでください_recognition.tsv",
        "module": "01-n5", "jlpt": "n5", "slug": "ないでください",
        "label": "ないでください (polite negative request)",
        "formula": "Verb[ない-stem] + ないでください",
        "contrast": "ないでください = polite request not to; てはいけない = strict prohibition",
        "rows": [
            ("写真を撮らないでください。", "しゃしんをとらないでください。",
             "Please don't take photos.",
             "ないでください: polite request directed at listener — don't do X",
             "polite no-photo"),
            ("ここに座らないでください。", "ここにすわらないでください。",
             "Please don't sit here.",
             "ないでください: location-specific polite negative request",
             "seat reserved"),
            ("窓を開けないでください、寒いですから。", "まどをあけないでください、さむいですから。",
             "Please don't open the window — it's cold.",
             "ないでください + reason: soft request with rationale",
             "cold weather"),
            ("心配しないでください、大丈夫です。", "しんぱいしないでください、だいじょうぶです。",
             "Please don't worry — it's all right.",
             "ないでください for emotions: reassuring the listener",
             "reassurance"),
            ("約束を忘れないでくださいね。", "やくそくをわすれないでくださいね。",
             "Please don't forget our promise.",
             "ないでくださいね: soft, reminder-style polite negative request",
             "friendly reminder"),
        ],
    },
    {
        "path": "grammar-strict/01-n5/なくてはいけない_recognition.tsv",
        "module": "01-n5", "jlpt": "n5", "slug": "なくてはいけない",
        "label": "なくてはいけない (must / have to)",
        "formula": "Verb[ない-stem] + なくてはいけない",
        "contrast": "なくてはいけない ≈ なければならない; てはいけない = must NOT",
        "rows": [
            ("明日は早く起きなくてはいけない。", "あしたははやくおきなくてはいけない。",
             "Tomorrow I have to wake up early.",
             "なくてはいけない: situation-driven obligation (planned)",
             "early start"),
            ("薬を毎日飲まなくてはいけません。", "くすりをまいにちのまなくてはいけません。",
             "I have to take medicine every day.",
             "なくてはいけません: medical/routine obligation",
             "daily medication"),
            ("宿題を出さなくてはいけない。", "しゅくだいをださなくてはいけない。",
             "I have to hand in the homework.",
             "なくてはいけない: school-imposed obligation",
             "homework due"),
            ("会議に出席しなくてはいけません。", "かいぎにしゅっせきしなくてはいけません。",
             "I have to attend the meeting.",
             "なくてはいけません: work obligation",
             "must attend meeting"),
            ("家賃を月末までに払わなくてはいけない。", "やちんをげつまつまでにはらわなくてはいけない。",
             "I have to pay rent by the end of the month.",
             "なくてはいけない: deadline-driven obligation",
             "rent deadline"),
        ],
    },

    # ───────────────────── N4 ─────────────────────
    {
        "path": "grammar-strict/02-n4/かもしれない_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "かもしれない",
        "label": "かもしれない (might / possibly)",
        "formula": "Verb/Adj[plain] / N + かもしれない",
        "contrast": "かもしれない = uncertain possibility; に違いない = certain",
        "rows": [
            ("明日は雨が降るかもしれない。", "あしたはあめがふるかもしれない。",
             "It might rain tomorrow.",
             "かもしれない: weather forecast — speculative possibility",
             "weather guess"),
            ("彼はもう帰ったかもしれません。", "かれはもうかえったかもしれません。",
             "He might have already gone home.",
             "Verb-た + かもしれない: past possibility",
             "past possibility"),
            ("この問題は難しいかもしれない。", "このもんだいはむずかしいかもしれない。",
             "This problem might be difficult.",
             "Adj-い + かもしれない: tentative judgment",
             "guessed difficulty"),
            ("彼女は学生かもしれません。", "かのじょはがくせいかもしれません。",
             "She might be a student.",
             "N + かもしれない: identity guess",
             "guessing role"),
            ("間に合わないかもしれない。急ごう。", "まにあわないかもしれない。いそごう。",
             "We might not make it in time. Let's hurry.",
             "Verb-negative + かもしれない: speculation triggers action",
             "fear of being late"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/がる_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "がる",
        "label": "がる (show signs of / appear to feel)",
        "formula": "Adj[stem] + がる; Verb-stem + たがる",
        "contrast": "Adj-がる = third-person feeling; bare Adj = own feeling",
        "rows": [
            ("子供が新しい服を欲しがっている。", "こどもがあたらしいふくをほしがっている。",
             "The child wants new clothes.",
             "欲しがる: external display of someone else's desire",
             "child wants clothes"),
            ("彼は寒がっているようだ。", "かれはさむがっているようだ。",
             "He seems to feel cold.",
             "寒がる: observed sensation in another person",
             "observing cold"),
            ("彼女はその話を聞いて怖がった。", "かのじょはそのはなしをきいてこわがった。",
             "She got scared hearing that story.",
             "怖がる: third-person fear response",
             "third-person fear"),
            ("妹は外で遊びたがっています。", "いもうとはそとであそびたがっています。",
             "My sister wants to play outside.",
             "Verb-stem + たがる: external display of desire to do X",
             "wants to play"),
            ("犬がしっぽを振って嬉しがる。", "いぬがしっぽをふってうれしがる。",
             "The dog wags its tail in delight.",
             "嬉しがる: animal/other shows joy outwardly",
             "happy dog"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/たところだ_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "たところだ",
        "label": "たところだ (just finished)",
        "formula": "Verb[た] + ところだ",
        "contrast": "たところだ = just now finished; たばかり = still recent feeling",
        "rows": [
            ("今、家に着いたところです。", "いま、いえについたところです。",
             "I just got home now.",
             "たところだ: action completed at the present moment",
             "just arrived"),
            ("ちょうどご飯を食べ終わったところだ。", "ちょうどごはんをたべおわったところだ。",
             "I just finished eating.",
             "たところだ: meal-completion right now",
             "just ate"),
            ("会議が終わったところです。", "かいぎがおわったところです。",
             "The meeting just finished.",
             "たところだ: event endpoint just reached",
             "meeting over"),
            ("今、彼から電話があったところだ。", "いま、かれからでんわがあったところだ。",
             "I just got a call from him.",
             "たところだ: external event at the present moment",
             "call just came"),
            ("仕事を始めたところで、お客が来ました。", "しごとをはじめたところで、おきゃくがきました。",
             "Just as I started working, a customer arrived.",
             "たところで: at the moment X happened, Y also did",
             "interrupted start"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/ていた_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "ていた",
        "label": "ていた (past progressive / habitual past)",
        "formula": "Verb[て] + いた",
        "contrast": "ていた = was V-ing (past); ている = is V-ing (present)",
        "rows": [
            ("昨日の夜、テレビを見ていた。", "きのうのよる、てれびをみていた。",
             "I was watching TV last night.",
             "ていた: ongoing past action at a specific time",
             "watching TV"),
            ("十年前は東京に住んでいました。", "じゅうねんまえはとうきょうにすんでいました。",
             "I was living in Tokyo ten years ago.",
             "住んでいた: extended past state — multi-year residence",
             "past residence"),
            ("彼女は子供の頃ピアノを習っていた。", "かのじょはこどものころぴあのをならっていた。",
             "She used to take piano lessons as a child.",
             "ていた: past habitual practice",
             "past habit"),
            ("電話が鳴ったとき、ご飯を作っていた。", "でんわがなったとき、ごはんをつくっていた。",
             "When the phone rang, I was making dinner.",
             "ていた: past activity interrupted by another event",
             "interrupted past"),
            ("私たちは長い間、彼を待っていた。", "わたしたちはながいあいだ、かれをまっていた。",
             "We had been waiting for him for a long time.",
             "ていた: extended past waiting",
             "long wait"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/ときいた_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "ときいた",
        "label": "と聞いた (I heard that)",
        "formula": "[clause/plain] + と聞いた",
        "contrast": "と聞いた = personal hearsay; そうだ = general hearsay",
        "rows": [
            ("彼が病気だと聞いた。", "かれがびょうきだときいた。",
             "I heard that he's sick.",
             "と聞いた: speaker received the information from someone",
             "hearing news"),
            ("会議は中止になったと聞きました。", "かいぎはちゅうしになったとききました。",
             "I heard that the meeting was cancelled.",
             "と聞きました: formal report of received information",
             "cancellation news"),
            ("店長から、明日は休みだと聞いた。", "てんちょうから、あしたはやすみだときいた。",
             "I heard from the manager that tomorrow is a day off.",
             "から + と聞いた: information source named explicitly",
             "from the manager"),
            ("試験は来週だと聞いていたが、変更になった。", "しけんはらいしゅうだときいていたが、へんこうになった。",
             "I had heard the exam was next week, but it's been changed.",
             "と聞いていた: previously held belief from hearsay",
             "outdated info"),
            ("噂で、彼が結婚したと聞いた。", "うわさで、かれがけっこんしたときいた。",
             "Through rumour, I heard he got married.",
             "噂で + と聞いた: hearsay via informal channels",
             "rumour mill"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/なければならない_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "なければならない",
        "label": "なければならない (must / must not fail to)",
        "formula": "Verb[ない-stem] + なければならない",
        "contrast": "なければならない = formal obligation; なくてはいけない = casual",
        "rows": [
            ("明日までに書類を提出しなければならない。", "あしたまでにしょるいをていしゅつしなければならない。",
             "I must submit the documents by tomorrow.",
             "なければならない: formal deadline obligation",
             "deadline submission"),
            ("ルールを守らなければなりません。", "るーるをまもらなければなりません。",
             "We must follow the rules.",
             "なければなりません: institutional / rule-based obligation",
             "rule compliance"),
            ("会員は会費を払わなければならない。", "かいいんはかいひをはらわなければならない。",
             "Members must pay the membership fee.",
             "なければならない: contractual obligation",
             "member duty"),
            ("健康のために、運動しなければならない。", "けんこうのために、うんどうしなければならない。",
             "I must exercise for my health.",
             "なければならない: self-imposed but rationalized obligation",
             "health obligation"),
            ("子供は親の言うことを聞かなければならない。", "こどもはおやのいうことをきかなければならない。",
             "Children must listen to their parents.",
             "なければならない: moral / social expectation",
             "moral duty"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/にみえる_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "にみえる",
        "label": "に見える (looks like / appears)",
        "formula": "N / Adj + に見える",
        "contrast": "に見える = visual appearance; らしい = inferred; ようだ = observed",
        "rows": [
            ("彼は若く見える。", "かれはわかくみえる。",
             "He looks young.",
             "Adj-く + 見える: physical appearance judgment",
             "looks young"),
            ("彼女は学生に見えます。", "かのじょはがくせいにみえます。",
             "She looks like a student.",
             "N + に見える: appearance suggests a category",
             "looks like student"),
            ("その建物は古いお寺に見える。", "そのたてものはふるいおてらにみえる。",
             "That building looks like an old temple.",
             "に見える: identification by visual cue",
             "looks like temple"),
            ("怒っているように見える。", "おこっているようにみえる。",
             "He looks like he's angry.",
             "ように見える: appearance suggests an emotional state",
             "looks angry"),
            ("元気そうに見えてよかった。", "げんきそうにみえてよかった。",
             "I'm glad you look healthy.",
             "そうに見える: visual sign of well-being",
             "looks healthy"),
        ],
    },
    {
        "path": "grammar-strict/02-n4/化する_recognition.tsv",
        "module": "02-n4", "jlpt": "n4", "slug": "化する",
        "label": "化する (-ize / become / transform into)",
        "formula": "Noun + 化する",
        "contrast": "化する = formal transformation; になる = generic 'become'",
        "rows": [
            ("社会が高齢化している。", "しゃかいがこうれいかしている。",
             "Society is aging.",
             "高齢化する: demographic transformation",
             "aging society"),
            ("古い工場が近代化された。", "ふるいこうじょうがきんだいかされた。",
             "The old factory was modernised.",
             "近代化する: industrial modernisation",
             "modernisation"),
            ("会議の内容が文章化された。", "かいぎのないようがぶんしょうかされた。",
             "The contents of the meeting were put into writing.",
             "文章化する: oral → written documentation",
             "documentation"),
            ("デジタル化が進んでいる。", "でじたるかがすすんでいる。",
             "Digitisation is progressing.",
             "デジタル化する: analog → digital transformation",
             "digitisation"),
            ("制度を簡素化する必要がある。", "せいどをかんそかするひつようがある。",
             "We need to simplify the system.",
             "簡素化する: process / system simplification",
             "simplification"),
        ],
    },

    # ───────────────────── N3 ─────────────────────
    {
        "path": "grammar-strict/03-n3/あり_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "あり",
        "label": "あり (formal/written form of ある)",
        "formula": "N + あり / Verb-連用形 + あり",
        "contrast": "あり = formal/literary; ある = standard; います ≠ inanimate",
        "rows": [
            ("経験ありの人を募集します。", "けいけんありのひとをぼしゅうします。",
             "We are recruiting people with experience.",
             "経験あり: noun + あり as a written-formal possession label",
             "job ad — experience required"),
            ("人生は山あり谷あり。", "じんせいはやまありたにあり。",
             "Life has ups and downs.",
             "山あり谷あり: literary set phrase using あり",
             "life saying"),
            ("免許あり、車所有の方歓迎。", "めんきょあり、くるましょゆうのかたかんげい。",
             "Licence holders with their own car welcome.",
             "免許あり: noun + あり as a job-listing qualification flag",
             "job listing"),
            ("出張あり、月に二回程度です。", "しゅっちょうあり、つきににかいていどです。",
             "Business trips required, about twice a month.",
             "出張あり: noun + あり in a description list",
             "job description"),
            ("これより先、危険ありにつき立入禁止。", "これよりさき、きけんありにつきたちいりきんし。",
             "Danger ahead — no entry permitted.",
             "危険あり: posted-sign condition reporting",
             "warning sign"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/こそ_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "こそ",
        "label": "こそ (emphasis particle — precisely / it is X that)",
        "formula": "N + こそ / 〜て + こそ",
        "contrast": "こそ = emphatic 'this/X precisely'; は = topic; が = subject",
        "rows": [
            ("今日こそ早く起きるぞ。", "きょうこそはやくおきるぞ。",
             "Today is the day I'll wake up early.",
             "今日こそ: emphasises 'this very day' over previous failed attempts",
             "self-resolve"),
            ("こちらこそ、よろしくお願いします。", "こちらこそ、よろしくおねがいします。",
             "Likewise, pleased to meet you.",
             "こちらこそ: 'the pleasure is precisely mine' — reciprocity emphasis",
             "polite reciprocity"),
            ("失敗してこそ、成長できる。", "しっぱいしてこそ、せいちょうできる。",
             "It is only through failure that we grow.",
             "Verb-てこそ: conditional emphasis — only when X, then Y",
             "growth via failure"),
            ("あなたこそ、本当のリーダーだ。", "あなたこそ、ほんとうのりーだーだ。",
             "You're the one who's a real leader.",
             "Pronoun + こそ: 'precisely you' — picking one entity out of many",
             "person-specific praise"),
            ("これこそ、私が探していた本です。", "これこそ、わたしがさがしていたほんです。",
             "This is exactly the book I was looking for.",
             "これこそ: 'this and no other' — picks one specific item",
             "exact match"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/てもかまわない_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "てもかまわない",
        "label": "てもかまわない (it's fine to / don't mind if)",
        "formula": "Verb[て] + も + かまわない",
        "contrast": "てもかまわない = OK with me; てもいい = neutral permission",
        "rows": [
            ("ここに座ってもかまいませんか。", "ここにすわってもかまいませんか。",
             "Do you mind if I sit here?",
             "てもかまわない (politely asking): seeking permission",
             "asking to sit"),
            ("窓を開けてもかまわない。", "まどをあけてもかまわない。",
             "I don't mind if you open the window.",
             "てもかまわない: speaker grants permission",
             "granting permission"),
            ("少し遅れてもかまいません。", "すこしおくれてもかまいません。",
             "I don't mind if you're a little late.",
             "てもかまいません: flexibility about timing",
             "flexible timing"),
            ("どんな服装でもかまわない。", "どんなふくそうでもかまわない。",
             "Any kind of clothing is fine.",
             "どんな + でもかまわない: any-X-is-OK",
             "no dress code"),
            ("聞いてもかまわないですか。", "きいてもかまわないですか。",
             "Is it OK if I ask?",
             "てもかまわない: polite request to perform an action",
             "asking permission to ask"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/に取って_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "に取って",
        "label": "にとって (for / from the standpoint of)",
        "formula": "N + にとって",
        "contrast": "にとって = stance/viewpoint; に対して = directed at; について = about",
        "rows": [
            ("私にとって家族は一番大切です。", "わたしにとってかぞくはいちばんたいせつです。",
             "For me, family is the most important.",
             "にとって: subjective evaluation from a viewpoint",
             "personal priority"),
            ("学生にとって試験はストレスだ。", "がくせいにとってしけんはすとれすだ。",
             "For students, exams are stressful.",
             "にとって: group-level subjective evaluation",
             "student stress"),
            ("これは私たちにとって大きな機会だ。", "これはわたしたちにとっておおきなきかいだ。",
             "This is a big opportunity for us.",
             "にとって: collective stance — 'as we see it'",
             "team opportunity"),
            ("子供にとって遊びは学びの一つだ。", "こどもにとってあそびはまなびのひとつだ。",
             "For children, play is one form of learning.",
             "にとって: category-level subjective truth",
             "child-developmental view"),
            ("彼にとっては難しい決断だった。", "かれにとってはむずかしいけつだんだった。",
             "For him, it was a difficult decision.",
             "にとっては (topicalised): personal challenge framing",
             "his perspective"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/のはxの方だ_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "のはxの方だ",
        "label": "のは X の方だ (it is X that / the one who…)",
        "formula": "[Adj/V-plain] + のは + N + の方だ",
        "contrast": "のは…の方だ = cleft emphasis (it is X that...); は = neutral topic",
        "rows": [
            ("間違っているのはあなたの方だ。", "まちがっているのはあなたのほうだ。",
             "It's you who is mistaken.",
             "のは…の方だ: cleft emphasis — picks out the responsible party",
             "you're the wrong one"),
            ("謝るべきなのは私の方です。", "あやまるべきなのはわたしのほうです。",
             "It's I who should apologise.",
             "のは…の方だ: cleft emphasis — claims responsibility",
             "self-blame"),
            ("驚いたのは彼の方だった。", "おどろいたのはかれのほうだった。",
             "It was he who was surprised.",
             "のは…の方だった: cleft emphasis in narrative past",
             "he was surprised"),
            ("先に質問したのはお客さんの方です。", "さきにしつもんしたのはおきゃくさんのほうです。",
             "It was the customer who asked first.",
             "のは…の方だ: highlights the chronological first actor",
             "customer asked first"),
            ("怒っているのは父の方だ。", "おこっているのはちちのほうだ。",
             "It's my father who is angry.",
             "のは…の方だ: identifies which person of two holds the state",
             "father angry, not mother"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/の姿_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "の姿",
        "label": "の姿 (the form/appearance/figure of)",
        "formula": "N + の姿",
        "contrast": "の姿 = visual form; の様子 = state/condition; の様 = manner",
        "rows": [
            ("子供たちの姿が見えなくなった。", "こどもたちのすがたがみえなくなった。",
             "The children's figures disappeared from sight.",
             "の姿: physical form / silhouette",
             "vanishing form"),
            ("制服姿の彼女がとても新鮮だった。", "せいふくすがたのかのじょがとてもしんせんだった。",
             "Her in-uniform appearance was very fresh.",
             "N-姿: clothing-specific form (worn presentation)",
             "in uniform"),
            ("成功した社長の姿が雑誌に載った。", "せいこうしたしゃちょうのすがたがざっしにのった。",
             "The successful president's image appeared in the magazine.",
             "の姿: public image / persona in media",
             "media image"),
            ("故郷の自然の姿を忘れない。", "こきょうのしぜんのすがたをわすれない。",
             "I won't forget the appearance of my hometown's nature.",
             "の姿: remembered visual form of a place",
             "memory of place"),
            ("彼の本当の姿は誰も知らない。", "かれのほんとうのすがたはだれもしらない。",
             "Nobody knows his true form.",
             "の姿: true identity / hidden self",
             "true self"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/の間に_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "の間に",
        "label": "の間に (during / while / between)",
        "formula": "N / Verb[plain] + 間に",
        "contrast": "の間に = within a specific period (event happens); の間 = throughout",
        "rows": [
            ("夏休みの間に旅行に行きました。", "なつやすみのあいだにりょこうにいきました。",
             "I went on a trip during summer vacation.",
             "の間に: punctual event within the period",
             "trip during break"),
            ("私が寝ている間に雨が降った。", "わたしがねているあいだにあめがふった。",
             "It rained while I was asleep.",
             "の間に: event occurred during another ongoing event",
             "rain while sleeping"),
            ("会議の間に電話があった。", "かいぎのあいだにでんわがあった。",
             "There was a phone call during the meeting.",
             "の間に: incoming event during a bounded interval",
             "interruption"),
            ("十年の間に技術が大きく進歩した。", "じゅうねんのあいだにぎじゅつがおおきくしんぽした。",
             "Technology advanced greatly over ten years.",
             "の間に: long span — within which a change occurs",
             "decade of progress"),
            ("二人の間に深い理解があった。", "ふたりのあいだにふかいりかいがあった。",
             "There was deep understanding between the two.",
             "の間に: 'between two parties' (spatial-relational use)",
             "mutual understanding"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/切る_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "切る",
        "label": "切る / 〜きる (do completely / finish off)",
        "formula": "Verb[stem] + きる",
        "contrast": "〜きる = complete action; 〜切れない = unable to complete",
        "rows": [
            ("マラソンを走り切った。", "まらそんをはしりきった。",
             "I ran through the entire marathon.",
             "走りきる: completed a long distance to the end",
             "marathon completion"),
            ("この本を一日で読み切った。", "このほんをいちにちでよみきった。",
             "I finished reading this book in one day.",
             "読みきる: read the whole book to completion",
             "book finished"),
            ("最後まで使い切ろう。", "さいごまでつかいきろう。",
             "Let's use it all up.",
             "使いきる: consume fully / use to the last bit",
             "use it up"),
            ("彼は責任を果たし切った。", "かれはせきにんをはたしきった。",
             "He fulfilled his responsibility completely.",
             "果たしきる: discharged a duty in full",
             "duty fulfilled"),
            ("夜遅くまで起き切っていた。", "よるおそくまでおききっていた。",
             "He stayed up completely until late.",
             "起ききる: stayed up to the very end of the night",
             "stayed up all night"),
        ],
    },
    {
        "path": "grammar-strict/03-n3/合う_recognition.tsv",
        "module": "03-n3", "jlpt": "n3", "slug": "合う",
        "label": "〜合う (mutual / reciprocal action)",
        "formula": "Verb[stem] + 合う",
        "contrast": "〜合う = mutual; 〜合わせる = causative (make X match)",
        "rows": [
            ("友達と励まし合っている。", "ともだちとはげましあっている。",
             "We're encouraging each other.",
             "励まし合う: reciprocal encouragement",
             "mutual support"),
            ("家族で助け合うことが大切だ。", "かぞくでたすけあうことがたいせつだ。",
             "It's important to help each other within the family.",
             "助け合う: mutual help among multiple actors",
             "family solidarity"),
            ("二人は十年も愛し合ってきた。", "ふたりはじゅうねんもあいしあってきた。",
             "The two have loved each other for ten years.",
             "愛し合う: long-term reciprocal affection",
             "long-term love"),
            ("会議で意見を出し合いましょう。", "かいぎでいけんをだしあいましょう。",
             "Let's share opinions in the meeting.",
             "出し合う: each party contributes to a common pool",
             "brainstorm"),
            ("お互いに尊敬し合っている。", "おたがいにそんけいしあっている。",
             "We respect each other.",
             "尊敬し合う: mutual respect between parties",
             "mutual respect"),
        ],
    },

    # ───────────────────── N2 ─────────────────────
    {
        "path": "grammar-strict/04-n2/が気になる_recognition.tsv",
        "module": "04-n2", "jlpt": "n2", "slug": "が気になる",
        "label": "が気になる (to feel concerned about / be bothered by)",
        "formula": "N + が気になる",
        "contrast": "が気になる = mental concern; が好き = liking",
        "rows": [
            ("試験の結果が気になる。", "しけんのけっかがきになる。",
             "I'm anxious about the exam results.",
             "が気になる: anticipatory anxiety about a future outcome",
             "exam anxiety"),
            ("彼の発言が気になっている。", "かれのはつげんがきになっている。",
             "I'm bothered by his remark.",
             "が気になっている: ongoing concern about something said",
             "his remark lingers"),
            ("彼女の体調が気になる。", "かのじょのたいちょうがきになる。",
             "I'm worried about her health.",
             "が気になる: caring concern about another's well-being",
             "concern for her"),
            ("新しい店が気になって、行ってみた。", "あたらしいみせがきになって、いってみた。",
             "I was curious about the new shop, so I tried it.",
             "が気になって: curiosity-driven action",
             "new shop curiosity"),
            ("彼の態度が気になって眠れない。", "かれのたいどがきになってねむれない。",
             "His attitude bothers me — I can't sleep.",
             "が気になって + neg consequence: distress blocks normal function",
             "lost sleep"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/とも_recognition.tsv",
        "module": "04-n2", "jlpt": "n2", "slug": "とも",
        "label": "とも (concessive: even if / no matter / granting)",
        "formula": "Verb[volitional] / Adj + とも",
        "contrast": "とも = formal concessive; ても = standard 'even if'",
        "rows": [
            ("何が起ころうとも、私は諦めない。", "なにがおころうとも、わたしはあきらめない。",
             "No matter what happens, I won't give up.",
             "Verb-volitional + とも: emphatic concessive",
             "unwavering"),
            ("どんなに辛くとも、続けるべきだ。", "どんなにつらくとも、つづけるべきだ。",
             "However hard it is, one should continue.",
             "Adj-く + とも: granting an extreme — even then…",
             "endure hardship"),
            ("遠かろうとも、必ず行きます。", "とおかろうとも、かならずいきます。",
             "Even if it's far, I will surely go.",
             "Adj-かろう + とも: granting an inconvenience",
             "going regardless"),
            ("失敗しようとも、挑戦することが大切だ。", "しっぱいしようとも、ちょうせんすることがたいせつだ。",
             "Even if you fail, it's important to challenge yourself.",
             "Verb-volitional + とも: granting a feared outcome",
             "value of trying"),
            ("お忙しいとも存じますが、ご返答ください。", "おいそがしいともぞんじますが、ごへんとうください。",
             "Although I know you are busy, please reply.",
             "Adj + とも: formal-letter concessive (とも存じます)",
             "formal request"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/に応じて_recognition.tsv",
        "module": "04-n2", "jlpt": "n2", "slug": "に応じて",
        "label": "に応じて (in response to / depending on)",
        "formula": "N + に応じて",
        "contrast": "に応じて = matches/varies with X; に従って = follows directionally",
        "rows": [
            ("お客様のご要望に応じて、商品を提供します。", "おきゃくさまのごようぼうにおうじて、しょうひんをていきょうします。",
             "We provide products in response to customer requests.",
             "に応じて: customer-driven product adaptation",
             "responsive service"),
            ("収入に応じて税金が変わる。", "しゅうにゅうにおうじてぜいきんがかわる。",
             "Taxes vary depending on income.",
             "に応じて: proportional variation",
             "tax bracket"),
            ("年齢に応じた服を選ぶ。", "ねんれいにおうじたふくをえらぶ。",
             "Choose clothes appropriate to your age.",
             "に応じた + N: 'appropriate-to-X' attributive",
             "age-appropriate"),
            ("状況に応じて対応を変える。", "じょうきょうにおうじてたいおうをかえる。",
             "We change our response depending on the situation.",
             "に応じて: situational adaptive behavior",
             "adaptive response"),
            ("能力に応じて仕事を割り当てる。", "のうりょくにおうじてしごとをわりあてる。",
             "We assign work according to ability.",
             "に応じて: meritocratic allocation",
             "work assignment"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/に沿って_recognition.tsv",
        "module": "04-n2", "jlpt": "n2", "slug": "に沿って",
        "label": "に沿って (along / following / in line with)",
        "formula": "N + に沿って",
        "contrast": "に沿って = follow a line/plan; に従って = obey/comply with",
        "rows": [
            ("川に沿って公園が広がっている。", "かわにそってこうえんがひろがっている。",
             "The park extends along the river.",
             "に沿って: spatial — extending alongside a line",
             "riverside park"),
            ("ガイドラインに沿って作業を進めます。", "がいどらいんにそってさぎょうをすすめます。",
             "We proceed with the work along the guidelines.",
             "に沿って: procedural adherence to a plan",
             "following guidelines"),
            ("計画に沿って、来月新製品を発売する。", "けいかくにそって、らいげつしんせいひんをはつばいする。",
             "Following the plan, we'll launch the new product next month.",
             "に沿って: plan-driven action",
             "plan execution"),
            ("お客様のご希望に沿って提案します。", "おきゃくさまのごきぼうにそってていあんします。",
             "We make proposals in line with your wishes.",
             "に沿って: tailoring to expressed preferences",
             "client wishes"),
            ("道に沿って歩いてください。", "みちにそってあるいてください。",
             "Please walk along the road.",
             "に沿って: physical motion alongside a path",
             "walk along road"),
        ],
    },
    {
        "path": "grammar-strict/04-n2/抜く_recognition.tsv",
        "module": "04-n2", "jlpt": "n2", "slug": "抜く",
        "label": "〜抜く (do thoroughly / persevere through)",
        "formula": "Verb[stem] + 抜く",
        "contrast": "〜抜く = endure to completion; 〜きる = finish completely",
        "rows": [
            ("最後まで走り抜いた。", "さいごまではしりぬいた。",
             "I ran all the way through to the end.",
             "走り抜く: endured a long run to completion",
             "endurance run"),
            ("難しい問題を考え抜いた末、答えが分かった。", "むずかしいもんだいをかんがえぬいたすえ、こたえがわかった。",
             "After thinking through the hard problem thoroughly, I found the answer.",
             "考え抜く: exhaustive deliberation",
             "deep thinking"),
            ("彼は最後までやり抜く人だ。", "かれはさいごまでやりぬくひとだ。",
             "He's a person who sees things through to the end.",
             "やり抜く: character trait — sees tasks through",
             "follow-through"),
            ("苦しみを耐え抜くしかない。", "くるしみをたえぬくしかない。",
             "We have no choice but to endure the suffering completely.",
             "耐え抜く: endure pain to the end",
             "endure pain"),
            ("十年の留学を生き抜いた。", "じゅうねんのりゅうがくをいきぬいた。",
             "He survived ten years of study abroad.",
             "生き抜く: survive a long ordeal",
             "survival"),
        ],
    },

    # ───────────────────── N1 ─────────────────────
    {
        "path": "grammar-strict/05-n1/adj限りだ_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "adj限りだ",
        "label": "Adj + 限りだ (extremely / I feel very ~)",
        "formula": "Adj[stem] + 限りだ",
        "contrast": "限りだ = first-person feeling at peak; この上ない = utmost objectively",
        "rows": [
            ("お会いできて嬉しい限りです。", "おあいできてうれしいかぎりです。",
             "I am extremely glad to meet you.",
             "嬉しい限りだ: peak first-person joy in a meeting",
             "extreme joy"),
            ("お元気そうで何よりですが、寂しい限りです。", "おげんきそうでなによりですが、さびしいかぎりです。",
             "I'm glad you're well, but I feel very lonely.",
             "寂しい限りだ: peak loneliness",
             "extreme loneliness"),
            ("お忙しいところお越しいただき、ありがたい限りです。", "おいそがしいところおこしいただき、ありがたいかぎりです。",
             "I am extremely grateful that you came despite being busy.",
             "ありがたい限りだ: peak gratitude (formal)",
             "extreme gratitude"),
            ("我が子の成長は心強い限りだ。", "わがこのせいちょうはこころづよいかぎりだ。",
             "My child's growth is extremely reassuring.",
             "心強い限りだ: peak reassurance from a personal source",
             "reassurance from child"),
            ("お世話になり、嬉しい限りでございます。", "おせわになり、うれしいかぎりでございます。",
             "I am extremely happy to have your support.",
             "嬉しい限りでございます: peak joy in honorific register",
             "humble joy"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/ても差し支えない_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "ても差し支えない",
        "label": "ても差し支えない (it is no problem to / there is no objection)",
        "formula": "Verb[て] + も差し支えない",
        "contrast": "ても差し支えない = formal 'OK'; てもいい = casual permission",
        "rows": [
            ("こちらにご記入いただいても差し支えありません。", "こちらにごきにゅういただいてもさしつかえありません。",
             "It is no problem if you write here.",
             "ても差し支えない: formal grant of permission to write",
             "formal OK to write"),
            ("質問なさっても差し支えございません。", "しつもんなさってもさしつかえございません。",
             "Asking questions is no problem at all.",
             "ても差し支えない: honorific permission to ask",
             "honorific OK"),
            ("写真を撮っていただいても差し支えありません。", "しゃしんをとっていただいてもさしつかえありません。",
             "There is no problem in having you take photos.",
             "ても差し支えない: formal photo-permission grant",
             "OK to take photos"),
            ("少し遅れても差し支えないでしょうか。", "すこしおくれてもさしつかえないでしょうか。",
             "Would it be alright if I'm a little late?",
             "ても差し支えない: humble inquiry about tolerance",
             "asking tolerance"),
            ("詳細は後日でも差し支えない。", "しょうさいはごじつでもさしつかえない。",
             "Details can be addressed later — no objection.",
             "ても差し支えない: deferring with no objection",
             "deferral OK"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/であれ_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "であれ",
        "label": "であれ (even if it is / whatever / no matter what)",
        "formula": "N / Adj + であれ",
        "contrast": "であれ = formal concessive; でも = standard 'even'",
        "rows": [
            ("どんな理由であれ、暴力は許されない。", "どんなりゆうであれ、ぼうりょくはゆるされない。",
             "Whatever the reason, violence cannot be tolerated.",
             "どんな + N + であれ: 'whatever the X' — formal concessive",
             "violence — never"),
            ("失敗であれ成功であれ、経験になる。", "しっぱいであれせいこうであれ、けいけんになる。",
             "Whether failure or success, it becomes experience.",
             "X であれ Y であれ: granting both alternatives",
             "either way valuable"),
            ("誰であれ、ルールを守るべきだ。", "だれであれ、るーるをまもるべきだ。",
             "Whoever it is, they should follow the rules.",
             "誰であれ: 'whoever' — universal application",
             "rules apply to all"),
            ("どこであれ、私はあなたについていく。", "どこであれ、わたしはあなたについていく。",
             "Wherever it is, I will follow you.",
             "どこであれ: 'wherever' — universal location",
             "anywhere with you"),
            ("どんな仕事であれ、誠実に取り組む。", "どんなしごとであれ、せいじつにとりくむ。",
             "Whatever the work, I tackle it with sincerity.",
             "どんな + N + であれ: granting any category — same response",
             "sincere work"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/とばかり_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "とばかり",
        "label": "とばかり (as if to say / supposing only)",
        "formula": "Quoted-clause + とばかりに / N + とばかりに",
        "contrast": "とばかりに = 'as if to say X'; かのように = 'as if (simulated)'",
        "rows": [
            ("彼は当然だとばかりに胸を張った。", "かれはとうぜんだとばかりにむねをはった。",
             "He puffed out his chest as if to say 'Of course'.",
             "とばかりに: body language attributed to a quoted thought",
             "proud posture"),
            ("聞いていないよ、とばかりに首を振った。", "きいていないよ、とばかりにくびをふった。",
             "He shook his head as if to say 'I'm not listening'.",
             "とばかりに: nonverbal denial",
             "head-shake denial"),
            ("早く帰れ、とばかりにドアを指さした。", "はやくかえれ、とばかりにどあをゆびさした。",
             "He pointed at the door as if to say 'Get out'.",
             "とばかりに: gesture conveying an unspoken command",
             "pointing out"),
            ("褒めてくれ、とばかりに尻尾を振っている。", "ほめてくれ、とばかりにしっぽをふっている。",
             "It's wagging its tail as if to say 'praise me'.",
             "とばかりに: animal behaviour interpreted as a request",
             "dog wanting praise"),
            ("当然の権利だとばかりに、要求してきた。", "とうぜんのけんりだとばかりに、ようきゅうしてきた。",
             "He demanded it as if it were his obvious right.",
             "とばかりに: entitled demand framed as obvious",
             "entitled demand"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/ならばいざ知らず_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "ならばいざ知らず",
        "label": "ならいざ知らず (let alone / I don't know about X but…)",
        "formula": "N + (なら)いざ知らず",
        "contrast": "いざ知らず = 'not sure about X, but Y is…'; どころか = 'far from X'",
        "rows": [
            ("子供ならいざ知らず、大人がそんなことをするとは。", "こどもならいざしらず、おとながそんなことをするとは。",
             "I could understand a child, but for an adult to do that…",
             "ならいざ知らず: granting one case to highlight another",
             "expected of an adult"),
            ("新人ならいざ知らず、ベテランがミスをするのは問題だ。", "しんじんならいざしらず、べてらんがみすをするのはもんだいだ。",
             "A newcomer is one thing, but a veteran's mistake is a problem.",
             "ならいざ知らず: comparison contrast — different standards",
             "veteran mistake"),
            ("昔ならいざ知らず、今は誰もそんなことをしない。", "むかしならいざしらず、いまはだれもそんなことをしない。",
             "In the past, perhaps, but now no one does such a thing.",
             "ならいざ知らず: temporal contrast (then vs now)",
             "past vs present"),
            ("外国人ならいざ知らず、日本人なら知っているはずだ。", "がいこくじんならいざしらず、にほんじんならしっているはずだ。",
             "A foreigner is one thing, but a Japanese person should know.",
             "ならいざ知らず: in-group / out-group expectation contrast",
             "should know better"),
            ("お祭りならいざ知らず、平日にこんなに混むのは珍しい。", "おまつりならいざしらず、へいじつにこんなにこむのはめずらしい。",
             "A festival would be one thing, but it's rare to be this crowded on a weekday.",
             "ならいざ知らず: special occasion vs ordinary day",
             "unusual crowd"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/なりに_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "なりに",
        "label": "なりに (in one's own way)",
        "formula": "N + なりに / Verb[plain] + なりに",
        "contrast": "なりに = in X's own (limited) capacity; らしく = befitting X",
        "rows": [
            ("子供は子供なりに考えている。", "こどもはこどもなりにかんがえている。",
             "Children think in their own way.",
             "なりに: subject thinks within their own capacity / context",
             "child's perspective"),
            ("私なりに精一杯頑張った。", "わたしなりにせいいっぱいがんばった。",
             "I did my best in my own way.",
             "なりに: doing one's best with personal limits",
             "personal best"),
            ("貧しいなりに楽しい生活を送っている。", "まずしいなりにたのしいせいかつをおくっている。",
             "Though poor, they lead an enjoyable life in their own way.",
             "なりに: positive within stated limitation",
             "happy despite hardship"),
            ("彼は彼なりの考えがある。", "かれはかれなりのかんがえがある。",
             "He has his own way of thinking.",
             "なりの + N: 'one's own [kind of] X' — attributive form",
             "his own thinking"),
            ("若い人には若い人なりの悩みがある。", "わかいひとにはわかいひとなりのなやみがある。",
             "Young people have their own kinds of worries.",
             "なりの: group-specific concerns acknowledged",
             "generational concerns"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/に即して_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "に即して",
        "label": "に即して (in line with / based on actual circumstances)",
        "formula": "N + に即して",
        "contrast": "に即して = conforming to reality/facts; に基づいて = based on (foundation)",
        "rows": [
            ("現実に即した解決策を考える必要がある。", "げんじつにそくしたかいけつさくをかんがえるひつようがある。",
             "We need to think of a solution in line with reality.",
             "に即した: realistic / fact-conforming attributive",
             "realistic plan"),
            ("実態に即して政策を見直す。", "じったいにそくしてせいさくをみなおす。",
             "We review policy in line with the actual situation.",
             "に即して: policy reformed against on-the-ground reality",
             "policy review"),
            ("時代に即した教育が求められている。", "じだいにそくしたきょういくがもとめられている。",
             "Education in tune with the times is required.",
             "時代に即した: era-appropriate education",
             "modern education"),
            ("法律に即して処理されました。", "ほうりつにそくしてしょりされました。",
             "It was handled in accordance with the law.",
             "に即して: legal-compliance framing",
             "lawful handling"),
            ("事実に即して報告してください。", "じじつにそくしてほうこくしてください。",
             "Please report in line with the facts.",
             "に即して: factually accurate reporting",
             "factual report"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/びる_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "びる",
        "label": "〜びる (appear / take on a quality)",
        "formula": "Noun + びる",
        "contrast": "〜びる = visually/aesthetically resembles; 〜化する = transforms into",
        "rows": [
            ("彼は最近大人びてきた。", "かれはさいきんおとなびてきた。",
             "He's recently come to seem more adult.",
             "大人びる: visual / behavioural maturity surfacing",
             "growing up"),
            ("田舎びた風景が広がっていた。", "いなかびたふうけいがひろがっていた。",
             "A countryside-like landscape spread out before us.",
             "田舎びる: rural-like quality (attributive)",
             "countryside vibe"),
            ("年配びた話し方をする青年だった。", "ねんぱいびたはなしかたをするせいねんだった。",
             "He was a youth who spoke as if he were older.",
             "年配びる: speaking style suggests older age",
             "older-than-his-years"),
            ("古びた看板が懐かしい。", "ふるびたかんばんがなつかしい。",
             "The old-looking sign feels nostalgic.",
             "古びる: appearance of age / weathered look",
             "weathered sign"),
            ("勿体振らずに、率直に言ってほしい。", "もったいぶらずに、そっちょくにいってほしい。",
             "Don't put on airs — please say it plainly.",
             "勿体びる: putting on an air of importance",
             "stop posturing"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/ものと思う_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "ものと思う",
        "label": "ものと思う (believe / suppose that)",
        "formula": "Verb[plain] + ものと思う",
        "contrast": "ものと思う = settled belief; かもしれない = mere possibility",
        "rows": [
            ("彼は当然来るものと思っていた。", "かれはとうぜんくるものとおもっていた。",
             "I had assumed he would naturally come.",
             "ものと思う: settled prior expectation",
             "naive expectation"),
            ("仕事は順調に進むものと思っている。", "しごとはじゅんちょうにすすむものとおもっている。",
             "I believe the work will proceed smoothly.",
             "ものと思う: confident positive belief",
             "confident outlook"),
            ("もう問題は解決したものと思っていた。", "もうもんだいはかいけつしたものとおもっていた。",
             "I thought the problem had already been resolved.",
             "ものと思う: belief based on prior information",
             "resolved-already belief"),
            ("当然のことだと、皆ものと思っているようだ。", "とうぜんのことだと、みなものとおもっているようだ。",
             "Everyone seems to take it for granted.",
             "ものと思う: collective tacit assumption",
             "common assumption"),
            ("予定通り進むものと思っていただきたい。", "よていどおりすすむものとおもっていただきたい。",
             "I would like you to assume things proceed as planned.",
             "ものと思っていただく: humble request to assume",
             "humble assumption-ask"),
        ],
    },
    {
        "path": "grammar-strict/05-n1/んばかりに_recognition.tsv",
        "module": "05-n1", "jlpt": "n1", "slug": "んばかりに",
        "label": "んばかりに (as if to / on the verge of)",
        "formula": "Verb[ない-stem] + んばかりに",
        "contrast": "んばかりに = visible near-action; とばかりに = quoted-implied",
        "rows": [
            ("彼女は泣き出さんばかりに顔を歪めた。", "かのじょはなきださんばかりにかおをゆがめた。",
             "She twisted her face as if about to burst into tears.",
             "泣き出さんばかりに: on the verge of crying",
             "near-tears"),
            ("彼は怒鳴らんばかりに大声を出した。", "かれはどならんばかりにおおごえをだした。",
             "He shouted as if he were about to roar.",
             "怒鳴らんばかりに: on the verge of yelling",
             "near-shouting"),
            ("会場は溢れんばかりの人で埋まった。", "かいじょうはあふれんばかりのひとでうずまった。",
             "The venue was filled to the verge of overflowing with people.",
             "溢れんばかりの: on the verge of overflowing (attributive)",
             "packed venue"),
            ("子供は飛び跳ねんばかりに喜んだ。", "こどもはとびはねんばかりによろこんだ。",
             "The child was so delighted he seemed about to jump.",
             "飛び跳ねんばかりに: visible near-jumping joy",
             "extreme delight"),
            ("彼は土下座せんばかりに頭を下げた。", "かれはどげざせんばかりにあたまをさげた。",
             "He bowed as if about to prostrate himself.",
             "土下座せんばかりに: on the verge of dogeza",
             "deep bow"),
        ],
    },
]


def make_tsv(entry):
    deck_map = {"n5": "01 - N5", "n4": "02 - N4", "n3": "03 - N3",
                "n2": "04 - N2", "n1": "05 - N1"}
    deck = f"Japanese Grammar::{deck_map[entry['jlpt']]} Grammar::Recognition"
    header = (
        "#separator:tab\n"
        "#html:true\n"
        "#columns:JP\tReading\tEN\tLabel\tFormula\tMainUse\tQuickCue\tContrast\tAudio\tTags\n"
        "#notetype:Recognition\n"
        f"#deck:{deck}\n"
        "\n"
    )
    body = []
    for jp, reading, en, mainuse, quickcue in entry["rows"]:
        tags = (
            f"module:{entry['module']} "
            f"jlpt:{entry['jlpt']} "
            f"point:{entry['slug']} "
            f"complexity:standard "
            f"source:authored "
            f"frequency:top10k "
            f"scaffold:pending-audio"
        )
        body.append(
            f"{jp}\t{reading}\t{en}\t{entry['label']}\t{entry['formula']}\t"
            f"{mainuse}\t{quickcue}\t{entry['contrast']}\t\t{tags}\n"
        )
    return header + "".join(body)


def main():
    for entry in CONTENT:
        path = Path(entry["path"])
        path.write_text(make_tsv(entry), encoding="utf-8")
        print(f"  WROTE {path.name}  ({len(entry['rows'])} rows)")
    print(f"\nTotal: {len(CONTENT)} recognition files re-authored.")


if __name__ == "__main__":
    main()
